### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by Chrinkus** [Chrinkus/Next#4]
Before finalizing Version 1.0, review code to see if any redundancies or opportunities to abstract functionality to a constructor exist.

<s>Consider whether its worth applying barriers to restrict actor movement to within the canvas at this stage.</s>

**Comment by Chrinkus** [comment]
Fix tabs
Due to changes to vim config, code is indented well while editing but is awkward when viewed on GitHub. Re-tab/indent all lines to make code more readable.

**Comment by Chrinkus** [comment]
Consider amalgamating the two Menu.selectors into one inherited method. Most of the code references local variables so is it ok to add to the Menu.prototype from another module?

**Comment by Chrinkus** [comment]
That was a mess..

**Comment by Chrinkus** [comment]
Remove unused portions of actor.js and input.js. Create a player class that inherits from actor to keep movement updates specific to the player.

**Comment by davidwesst** [comment]
Code looks clean, and the object separation is well done. You had it right on finding a way to reuse a common object rather than worrying about multiple objects.

Suggestion: You should put all your objects into a namespace to ensure they don't collide with anything in the global scope.

You can add the following line to the top of each file that declares an object.

``` javascript
// this will extend your namespace object if it already exists, OR instantiate a new one
var MyNamespace = MyNamespace || { };
```

Then you add your object to the namespace:

``` javascript
MyNamespace.Menu = function() { 
    ///...code
}
```

It's simple, but it's something that ensures you don't bump into other objects. Generally I make `MyNamespace` something very short like `DW` to make it easy on me.

**NOTE***: this might have some impact on how you've declared variables and the like, so make sure you do some good testing to make sure everything works as it did, assuming you go this route.

**Comment by Chrinkus** [comment]
Will research this option and potential impact before implementing. Thanks Dave.
